name: nightcore

networks:
  nightcore-network:
    name: nightcore-network
    driver: bridge
    external: true

services:
  nightcore-dashboard-backend:
    image: nightcore-dashboard-backend:latest
    container_name: nightcore-dashboard-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    env_file:
      - .env

    volumes:
      - ./src/:/app/src/
      - ./main.py:/app/main.py

    networks:
      - nightcore-network

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard-backend.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.routers.dashboard-backend.priority=10"
      - "traefik.http.routers.dashboard-backend.entrypoints=websecure"
      - "traefik.http.routers.dashboard-backend.service=dashboard-backend"
      - "traefik.http.services.dashboard-backend.loadbalancer.server.port=${API_PORT}"
      - "traefik.http.routers.dashboard-backend.tls=true"